# Generated by Django 5.2.4 on 2025-07-24 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa_bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="confidence_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="corrected_answer",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="feedback_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="feedback_rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Poor"),
                    (2, "Fair"),
                    (3, "Good"),
                    (4, "Very Good"),
                    (5, "Excellent"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="human_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="is_corrected",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="FeedbackData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("original_answer", models.TextField()),
                ("corrected_answer", models.TextField(blank=True)),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("incorrect", "Incorrect Answer"),
                            ("incomplete", "Incomplete Answer"),
                            ("irrelevant", "Irrelevant Answer"),
                            ("good", "Good Answer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sources_used", models.JSONField(default=list)),
                ("confidence_score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qa_bot.chatsession",
                    ),
                ),
            ],
        ),
    ]
