# Generated by Django 5.2.4 on 2025-08-01 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa_bot", "0002_chatmessage_confidence_score_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QAWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_question", models.TextField()),
                ("generated_answer", models.TextField()),
                ("refined_answer", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generated", "Generated"),
                            ("pending_review", "Pending Human Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("refined", "Refined"),
                        ],
                        default="generated",
                        max_length=20,
                    ),
                ),
                ("human_feedback", models.TextField(blank=True)),
                ("chat_context", models.JSONField(default=list)),
                ("sources", models.JSONField(default=list)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa_workflows",
                        to="qa_bot.chatsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HumanReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "qa_workflow",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="qa_bot.qaworkflow",
                    ),
                ),
            ],
        ),
    ]
