# Generated by Django 5.2.4 on 2025-08-03 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa_bot", "0003_qaworkflow_humanreview"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatsession",
            old_name="awaiting_source",
            new_name="is_awaiting_source",
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="confidence_score",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="feedbackdata",
            name="confidence_score",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="qaworkflow",
            name="confidence_score",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
    ]
