# Generated by Django 5.2.4 on 2025-08-07 17:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "qa_bot",
            "0004_rename_awaiting_source_chatsession_is_awaiting_source_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="NodeExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("execution_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("thread_id", models.CharField(db_index=True, max_length=100)),
                ("node_name", models.CharField(max_length=50)),
                ("input_data", models.JSONField(default=dict)),
                ("output_data", models.JSONField(default=dict)),
                ("runtime_ms", models.IntegerField(default=0)),
                ("dependencies", models.JSONField(default=list)),
                ("cache_key", models.CharField(db_index=True, max_length=255)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["thread_id", "executed_at"],
                        name="qa_bot_node_thread__7b6d47_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExecutionCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkpoint_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("thread_id", models.CharField(db_index=True, max_length=100)),
                ("state_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "node_executions",
                    models.ManyToManyField(blank=True, to="qa_bot.nodeexecution"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["thread_id", "created_at"],
                        name="qa_bot_exec_thread__27e1b9_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SessionTree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("thread_id", models.CharField(db_index=True, max_length=100)),
                (
                    "node_type",
                    models.CharField(
                        choices=[("question", "Question"), ("response", "Response")],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="qa_bot.sessiontree",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["thread_id", "created_at"],
                        name="qa_bot_sess_thread__93fb90_idx",
                    )
                ],
            },
        ),
    ]
